HISSE_ISIMLERI = {
    # ── BIST ──────────────────────────────────────────────────────────────
    "THYAO.IS": "Türk Hava Yolları",
    "GARAN.IS": "Garanti BBVA Bankası",
    "ASELS.IS": "Aselsan Elektronik",
    "EREGL.IS": "Ereğli Demir ve Çelik",
    "KCHOL.IS": "Koç Holding",
    "AKBNK.IS": "Akbank",
    "YKBNK.IS": "Yapı ve Kredi Bankası",
    "SISE.IS": "Şişe Cam",
    "BIMAS.IS": "BİM Birleşik Mağazalar",
    "FROTO.IS": "Ford Otosan",
    "TOASO.IS": "Tofaş Oto Fabrikası",
    "SAHOL.IS": "Sabancı Holding",
    "PETKM.IS": "Petkim Petrokimya",
    "TUPRS.IS": "Tüpraş",
    "ARCLK.IS": "Arçelik",
    "TCELL.IS": "Turkcell",
    "HALKB.IS": "Halkbank",
    "VAKBN.IS": "Vakıfbank",
    "ISCTR.IS": "İş Bankası",
    "PGSUS.IS": "Pegasus Hava Taşımacılığı",
    "EKGYO.IS": "Emlak Konut GYO",
    "KRDMD.IS": "Kardemir",
    "KOZAL.IS": "Koza Altın",
    "KOZAA.IS": "Koza Anadolu Metal",
    "ODAS.IS": "Odaş Elektrik",
    "SASA.IS": "Sasa Polyester",
    "TAVHL.IS": "TAV Havalimanları",
    "VESTL.IS": "Vestel Elektronik",
    "SOKM.IS": "Şok Marketler",
    "MGROS.IS": "Migros Ticaret",
    "GUBRF.IS": "Gübre Fabrikaları",
    "CIMSA.IS": "Çimsa Çimento",
    "ENKAI.IS": "Enka İnşaat",
    "LOGO.IS": "Logo Yazılım",
    "ULKER.IS": "Ülker Bisküvi",
    "AKSEN.IS": "Aksa Enerji",
    "DOHOL.IS": "Doğan Holding",
    "TTKOM.IS": "Türk Telekom",
    "CWENE.IS": "Çalık Enerji (CW Enerji)",
    "KONTR.IS": "Kontrolmatik Teknoloji",
    "ALARK.IS": "Alarko Holding",
    "ANACM.IS": "Anadolu Cam",
    "AEFES.IS": "Anadolu Efes Biracılık",
    "BERA.IS": "Bera Holding",
    "BRISA.IS": "Brisa Bridgestone",
    "BUCIM.IS": "Bursa Çimento",
    "CCOLA.IS": "Coca-Cola İçecek",
    "DOAS.IS": "Doğuş Otomotiv",
    "ECZYT.IS": "Eczacıbaşı Yatırım",
    "EGEEN.IS": "Ege Endüstri",
    "EUPWR.IS": "Europower Enerji",
    "FENER.IS": "Fenerbahçe Futbol",
    "GSRAY.IS": "Galatasaray Sportif",
    "HEKTS.IS": "Hektaş Ticaret",
    "HLGYO.IS": "Halk GYO",
    "INDES.IS": "İndeks Bilgisayar",
    "ISDMR.IS": "İskenderun Demir Çelik",
    "ISGYO.IS": "İş GYO",
    "KAREL.IS": "Karel Elektronik",
    "KARSN.IS": "Karsan Otomotiv",
    "KARTN.IS": "Kartonsan",
    "KENT.IS": "Kent Gıda",
    "KLMSN.IS": "Klimasan Klima",
    "KONYA.IS": "Konya Çimento",
    "KORDS.IS": "Kordsa Teknik Tekstil",
    "KRDMA.IS": "Kardemir A",
    "KRDMB.IS": "Kardemir B",
    "LIDER.IS": "Lider Faktoring",
    "MAVI.IS": "Mavi Giyim",
    "MERCN.IS": "Mercan Kimya",
    "METRO.IS": "Metro Ticaret",
    "MPARK.IS": "MLP Sağlık Hizmetleri",
    "NATEN.IS": "Naturel Enerji",
    "NETAS.IS": "Netaş Telekomünikasyon",
    "NTGAZ.IS": "Naturelgaz",
    "NTHOL.IS": "Net Holding",
    "NUHCM.IS": "Nuh Çimento",
    "ORGE.IS": "Orge Enerji",
    "OTKAR.IS": "Otokar Otobüs",
    "OYAKC.IS": "Oyak Çimento",
    "PARSN.IS": "Parsan Makine",
    "PENTA.IS": "Penta Teknoloji",
    "PETUN.IS": "Pınar Et ve Un",
    "PINSU.IS": "Pınar Su",
    "POLHO.IS": "Polisan Holding",
    "QNBFB.IS": "QNB Finansbank",
    "RAYSG.IS": "Ray Sigorta",
    "RYSAS.IS": "Reysaş Lojistik",
    "SAFKR.IS": "Şafak Kırtasiye",
    "SANEL.IS": "Sanel Elektrik",
    "SANFM.IS": "Sanifoam",
    "SANKO.IS": "Sanko Holding",
    "SARKY.IS": "Sarkuysan Elektrolitik Bakır",
    "SELEC.IS": "Selçuk Ecza",
    "SELGD.IS": "Selçuk Gıda",
    "SILVR.IS": "Silverline Endüstri",
    "SNGYO.IS": "Sinpaş GYO",
    "SODSN.IS": "Sodaş Sodyum",
    "TATGD.IS": "Tat Gıda",
    "TBORG.IS": "Türk Tuborg",
    "TKFEN.IS": "Tekfen Holding",
    "TMSN.IS": "Tümosan Motor",
    "TRGYO.IS": "Torunlar GYO",
    "TSKB.IS": "Türkiye Sınai Kalkınma Bankası",
    "TTRAK.IS": "Türk Traktör",
    "TURSG.IS": "Türkiye Sigorta",
    "ULUUN.IS": "Ulusal Un",
    "ULUSE.IS": "Ulusoy Elektrik",
    "UNLU.IS": "Ünlü Yatırım",
    "VAKKO.IS": "Vakko Tekstil",
    "VESBE.IS": "Vestel Beyaz Eşya",
    "YAPRK.IS": "Yaprak Süt",
    "YATAS.IS": "Yataş Yatak",
    "YUNSA.IS": "Yünsa Yünlü Sanayi",
    "ZOREN.IS": "Zorlu Enerji",
    "AGHOL.IS": "AG Anadolu Grubu Holding",
    "AGESA.IS": "AgeSA Hayat ve Emeklilik",
    "ALBRK.IS": "Albaraka Türk",
    "AYDEM.IS": "Aydem Enerji",
    "AYEN.IS": "Ayen Enerji",
    "BAGFS.IS": "Bagfaş Gübre",
    "BANVT.IS": "Banvit Bandırma Vitaminli",
    "BIENY.IS": "Bien Yenilenebilir Enerji",
    "BIZIM.IS": "Bizim Toptan Satış",
    "GENIL.IS": "Gen İlaç",
    "GEREL.IS": "Gerçek Elektrik",
    "GOLTS.IS": "Göltaş Göller Bölgesi",
    "GOODY.IS": "Goodyear Lastikleri",
    "GOZDE.IS": "Gözde Girişim",
    "GRSEL.IS": "Gürsel Turizm",
    "GSDHO.IS": "GSD Holding",
    "GWIND.IS": "Galata Wind Enerji",
    "HUBVC.IS": "Hub Girişim",
    "ISATR.IS": "İş Yatırım",
    "JANTS.IS": "Jantsa Jant",
    "KATMR.IS": "Katmerciler Araç",
    "KCAER.IS": "Kocaer Çelik",
    "KERVT.IS": "Kerevitaş Gıda",
    "KRONT.IS": "Kronos Bilişim",
    "KSTUR.IS": "Kuştur Kuşadası Turizm",
    "KUTPO.IS": "Kütahya Porselen",
    "MEDTR.IS": "Meditera Tıbbi Malzeme",
    "MIATK.IS": "Mia Teknoloji",
    "MNDRS.IS": "Menderes Tekstil",
    "MOBTL.IS": "Mobtelecom",
    "MRDIN.IS": "Mardin Çimento",
    "MRSHL.IS": "Marshall Boya",
    "PKART.IS": "Plastikkart",
    "RGYAS.IS": "Reğa Yatırım",
    "SUWEN.IS": "Süwen İç Giyim",
    "TATEN.IS": "Tatex Enerji",
    "TKNSA.IS": "Teknosa İç ve Dış",
    "TUCLK.IS": "Tucluk Enerji",
    "UMTAS.IS": "Ümraniye Tıbbi Atık",
    "USAK.IS": "Uşak Seramik",
    "VAKFN.IS": "Vakıf Finansal Kiralama",
    "YEOTK.IS": "Yeo Teknoloji",
    "YGYO.IS": "Yeni Gimat GYO",
    "ASTOR.IS": "Astor Enerji",
    "ALFAS.IS": "Alfa Solar Enerji",
    "REEDR.IS": "Reeder Teknoloji",
    "TABGD.IS": "Tab Gıda",
    "KALES.IS": "Kaleseramik",
    "ENERY.IS": "Enerya Enerji",
    "IZENR.IS": "İzdemir Enerji",
    "OFSYM.IS": "Ofis Yem Gıda",
    "HATSN.IS": "Hat-San Gemi İnşaa",
    "DOFER.IS": "Dofer Yapı Malzemeleri",
    "BYDNR.IS": "Baydöner Restoranları",
    "KLSER.IS": "Kaleseramik",
    "MEKAG.IS": "Meka Beton Santralleri",
    "TARKM.IS": "Tarkim Bitki Koruma",
    "GIPTA.IS": "Gıpta Ofis Kırtasiye",
    "BEGYO.IS": "Batı Ege GYO",
    "FZLGY.IS": "Fuzul GYO",
    "ASCE.IS": "Asce GYO",
    "PASEU.IS": "Pasifik Eurasia Lojistik",
    "CVKMD.IS": "CVK Maden İşletmeleri",
    "GRTRK.IS": "Graınturk Tarım",
    "BIGCH.IS": "Bigchefs (Büyük Şefler)",
    "KOPOL.IS": "Koza Polyester",
    "FORTE.IS": "Forte Bilgi İletişim",
    "A1CAP.IS": "A1 Capital Yatırım",
    "KTNTR.IS": "Koton Tekstil",
    "BRSAN.IS": "Borusan Mannesmann",
    "ISMEN.IS": "İş Yatırım Menkul Değerler",
    "SKBNK.IS": "Şekerbank",
    "YYAPI.IS": "Yeşil Yapı",
    "TRILC.IS": "Türk İlaç ve Serum Sanayi",
    "PRKAB.IS": "Türk Prysmian Kablo",
    "GESAN.IS": "Girişim Elektrik Sanayi",
    "SMRTG.IS": "Smart Güneş Teknolojileri",
    "YYLGA.IS": "Yayla Agro Gıda",
    "AHGAZ.IS": "Ahlatcı Doğalgaz",
    "CANTE.IS": "Çan2 Termik",
    "HKTM.IS": "Hidropar Hareket Kontrol",
    "KMPUR.IS": "Kimteks Poliüretan",
    "PNLSN.IS": "Panelsan Çatı Cephe",
    "RUBNS.IS": "Rubenis Tekstil",
    "SUNTK.IS": "Sun Tekstil",
    "TUREX.IS": "Turex Turizm",
    "ZEDUR.IS": "Zedur Enerji",
    "BJKAS.IS": "Beşiktaş Futbol Yatırımları",
    "TSPOR.IS": "Trabzonspor Sportif",

    # ── ABD ──────────────────────────────────────────────────────────
    "AAPL": "Apple Inc.",
    "MSFT": "Microsoft Corporation",
    "GOOGL": "Alphabet Inc. (Google) A",
    "GOOG": "Alphabet Inc. (Google) C",
    "AMZN": "Amazon.com Inc.",
    "NVDA": "NVIDIA Corporation",
    "META": "Meta Platforms (Facebook)",
    "TSLA": "Tesla Inc.",
    "BRK-B": "Berkshire Hathaway B",
    "JPM": "JPMorgan Chase & Co.",
    "JNJ": "Johnson & Johnson",
    "V": "Visa Inc.",
    "PG": "Procter & Gamble",
    "MA": "Mastercard Inc.",
    "HD": "The Home Depot",
    "CVX": "Chevron Corporation",
    "MRK": "Merck & Co.",
    "ABBV": "AbbVie Inc.",
    "PEP": "PepsiCo Inc.",
    "KO": "The Coca-Cola Company",
    "BAC": "Bank of America",
    "WMT": "Walmart Inc.",
    "XOM": "ExxonMobil Corporation",
    "LLY": "Eli Lilly and Company",
    "TMO": "Thermo Fisher Scientific",
    "COST": "Costco Wholesale",
    "AVGO": "Broadcom Inc.",
    "MCD": "McDonald's Corporation",
    "ACN": "Accenture PLC",
    "DHR": "Danaher Corporation",
    "NEE": "NextEra Energy",
    "UNH": "UnitedHealth Group",
    "AMD": "Advanced Micro Devices",
    "QCOM": "Qualcomm Inc.",
    "ADBE": "Adobe Inc.",
    "TXN": "Texas Instruments",
    "INTC": "Intel Corporation",
    "CSCO": "Cisco Systems",
    "INTU": "Intuit Inc.",
    "AMAT": "Applied Materials",
    "PYPL": "PayPal Holdings",
    "MU": "Micron Technology",
    "LRCX": "Lam Research",
    "SBUX": "Starbucks Corporation",
    "MDLZ": "Mondelez International",
    "REGN": "Regeneron Pharmaceuticals",
    "KLAC": "KLA Corporation",
    "SNPS": "Synopsys Inc.",
    "CDNS": "Cadence Design Systems",
    "MRVL": "Marvell Technology",
    "CRM": "Salesforce Inc.",
    "NOW": "ServiceNow Inc.",
    "SNOW": "Snowflake Inc.",
    "PLTR": "Palantir Technologies",
    "UBER": "Uber Technologies",
    "ABNB": "Airbnb Inc.",
    "DASH": "DoorDash Inc.",
    "RBLX": "Roblox Corporation",
    "COIN": "Coinbase Global",
    "SQ": "Block Inc. (Square)",
    "SHOP": "Shopify Inc.",
    "SPOT": "Spotify Technology",
    "PINS": "Pinterest Inc.",
    "SNAP": "Snap Inc.",
    "ZM": "Zoom Video Communications",
    "DOCU": "DocuSign Inc.",
    "OKTA": "Okta Inc.",
    "CRWD": "CrowdStrike Holdings",
    "ZS": "Zscaler Inc.",
    "NET": "Cloudflare Inc.",
    "DDOG": "Datadog Inc.",
    "MDB": "MongoDB Inc.",
    "GTLB": "GitLab Inc.",
    "BILL": "Bill.com Holdings",
    "HUBS": "HubSpot Inc.",
    "VEEV": "Veeva Systems",
    "WDAY": "Workday Inc.",
    "TEAM": "Atlassian Corporation",
    "PANW": "Palo Alto Networks",
    "FTNT": "Fortinet Inc.",
    "MELI": "MercadoLibre Inc.",
    "PDD": "PDD Holdings (Temu)",
    "BABA": "Alibaba Group",
    "JD": "JD.com Inc.",
    "SE": "Sea Limited",
    "ASML": "ASML Holding",
    "GS": "Goldman Sachs",
    "MS": "Morgan Stanley",
    "C": "Citigroup Inc.",
    "WFC": "Wells Fargo & Company",
    "USB": "U.S. Bancorp",
    "PNC": "PNC Financial Services",
    "TFC": "Truist Financial",
    "COF": "Capital One Financial",
    "AXP": "American Express",
    "BK": "Bank of New York Mellon",
    "SCHW": "Charles Schwab",
    "BLK": "BlackRock Inc.",
    "ICE": "Intercontinental Exchange",
    "CME": "CME Group",
    "MCO": "Moody's Corporation",
    "SPGI": "S&P Global Inc.",
    "CVS": "CVS Health Corporation",
    "CI": "Cigna Group",
    "HUM": "Humana Inc.",
    "CNC": "Centene Corporation",
    "HCA": "HCA Healthcare",
    "PFE": "Pfizer Inc.",
    "BMY": "Bristol-Myers Squibb",
    "GILD": "Gilead Sciences",
    "BIIB": "Biogen Inc.",
    "VRTX": "Vertex Pharmaceuticals",
    "MRNA": "Moderna Inc.",
    "BNTX": "BioNTech SE",
    "ALNY": "Alnylam Pharmaceuticals",
    "BA": "Boeing Company",
    "LMT": "Lockheed Martin",
    "RTX": "RTX Corporation (Raytheon)",
    "NOC": "Northrop Grumman",
    "GD": "General Dynamics",
    "TDG": "TransDigm Group",
    "CAT": "Caterpillar Inc.",
    "DE": "Deere & Company",
    "EMR": "Emerson Electric",
    "HON": "Honeywell International",
    "MMM": "3M Company",
    "GE": "GE Aerospace",
    "ETN": "Eaton Corporation",
    "ROK": "Rockwell Automation",
    "AME": "Ametek Inc.",
    "PH": "Parker-Hannifin",
    "COP": "ConocoPhillips",
    "SLB": "SLB (Schlumberger)",
    "HAL": "Halliburton Company",
    "BKR": "Baker Hughes",
    "MPC": "Marathon Petroleum",
    "VLO": "Valero Energy",
    "PSX": "Phillips 66",
    "OXY": "Occidental Petroleum",
    "GM": "General Motors",
    "F": "Ford Motor Company",
    "TGT": "Target Corporation",
    "KR": "Kroger Co.",
    "DG": "Dollar General",
    "DLTR": "Dollar Tree Inc.",
    "ROST": "Ross Stores",
    "TJX": "TJX Companies",
    "EBAY": "eBay Inc.",
    "ETSY": "Etsy Inc.",
    "CHWY": "Chewy Inc.",
    "TMUS": "T-Mobile US",
    "VZ": "Verizon Communications",
    "T": "AT&T Inc.",
    "DIS": "The Walt Disney Company",
    "CMCSA": "Comcast Corporation",
    "PARA": "Paramount Global",
    "WBD": "Warner Bros. Discovery",
    "LVS": "Las Vegas Sands",
    "MGM": "MGM Resorts International",
    "WYNN": "Wynn Resorts",
    "CZR": "Caesars Entertainment",
    "NKE": "Nike Inc.",
    "LULU": "Lululemon Athletica",
    "PVH": "PVH Corp. (Calvin Klein)",
    "RL": "Ralph Lauren",
    "VFC": "VF Corporation",
    "ANF": "Abercrombie & Fitch",
    "NFLX": "Netflix Inc.",
    "PATH": "UiPath Inc.",
    "MSTR": "MicroStrategy Inc.",
    "DKNG": "DraftKings Inc.",
    "HOOD": "Robinhood Markets",
    "ARM": "ARM Holdings PLC",
    "SMCI": "Super Micro Computer",
    "RDDT": "Reddit Inc.",
    "AI": "C3.ai Inc.",
    "U": "Unity Software",
    "COUP": "Coupa Software",
    "CRSR": "Corsair Gaming",
    "AFRM": "Affirm Holdings",
    "UPST": "Upstart Holdings",
    "RIVN": "Rivian Automotive",
    "LCID": "Lucid Group",
    "SOFI": "SoFi Technologies",
    "PLUG": "Plug Power",
    "ENPH": "Enphase Energy",
    "FSLR": "First Solar",
    "SEDG": "SolarEdge Technologies",
    "RUN": "Sunrun Inc.",
    "ASTS": "AST SpaceMobile",
    "CELH": "Celsius Holdings",
    "APP": "AppLovin Corp",
    "SYM": "Symbotic Inc.",
    "EA": "Electronic Arts",
    "TTWO": "Take-Two Interactive",
    "ISRG": "Intuitive Surgical",
    "ILMN": "Illumina Inc.",
    "DXCM": "DexCom Inc.",
    "CTSH": "Cognizant Technology",
    "CDW": "CDW Corporation",
    "AKAM": "Akamai Technologies",
    "CHKP": "Check Point Software",
    "GEN": "Gen Digital",
    "SWKS": "Skyworks Solutions",
    "QRVO": "Qorvo Inc.",
    "MPWR": "Monolithic Power Systems",
    "ON": "ON Semiconductor",
    "MCHP": "Microchip Technology",
    "NXPI": "NXP Semiconductors",
    "KDP": "Keurig Dr Pepper",
    "CHTR": "Charter Communications",
    "MAR": "Marriott International",

    # ── KRİPTO PARALAR ─────────────────────────────────────────────────
    "BTCUSDT": "Bitcoin (BTC)",
    "ETHUSDT": "Ethereum (ETH)",
    "BNBUSDT": "Binance Coin (BNB)",
    "SOLUSDT": "Solana (SOL)",
    "XRPUSDT": "Ripple (XRP)",
    "ADAUSDT": "Cardano (ADA)",
    "AVAXUSDT": "Avalanche (AVAX)",
    "DOGEUSDT": "Dogecoin (DOGE)",
    "DOTUSDT": "Polkadot (DOT)",
    "LINKUSDT": "Chainlink (LINK)",
    "MATICUSDT": "Polygon (MATIC)",
    "SHIBUSDT": "Shiba Inu (SHIB)",
    "LTCUSDT": "Litecoin (LTC)",
    "TRXUSDT": "TRON (TRX)",
    "UNIUSDT": "Uniswap (UNI)",
    "ATOMUSDT": "Cosmos (ATOM)",
    "ETCUSDT": "Ethereum Classic (ETC)",
    "XLMUSDT": "Stellar (XLM)",
    "ALGOUSDT": "Algorand (ALGO)",
    "NEARUSDT": "NEAR Protocol",
    "VETUSDT": "VeChain (VET)",
    "FILUSDT": "Filecoin (FIL)",
    "ICPUSDT": "Internet Computer (ICP)",
    "EGLDUSDT": "MultiversX (EGLD)",
    "SANDUSDT": "The Sandbox (SAND)",
    "THETAUSDT": "Theta Network",
    "AXSUSDT": "Axie Infinity (AXS)",
    "MANAUSDT": "Decentraland (MANA)",
    "AAVEUSDT": "Aave (AAVE)",
    "FTMUSDT": "Fantom (FTM)",
    "PEPEUSDT": "Pepe Coin (PEPE)",
    "WIFUSDT": "Dogwifhat (WIF)",
    "FLOKIUSDT": "Floki Inu (FLOKI)",
    "BONKUSDT": "Bonk (BONK)",
    "RENDERUSDT": "Render Token",
    "INJUSDT": "Injective (INJ)",
    "SUIUSDT": "Sui Network (SUI)",
    "APTUSDT": "Aptos (APT)",
    "ARBUSDT": "Arbitrum (ARB)",
    "OPUSDT": "Optimism (OP)",
    "STRKUSDT": "Starknet (STRK)",
    "ZKUSDT": "ZKSync (ZK)",
    "ENAUSDT": "Ethena (ENA)",
    "ETHFIUSDT": "Ether.fi (ETHFI)",
    "TAOUSDT": "Bittensor (TAO)",
    "SAGAUSDT": "Saga (SAGA)",
    "TNSRUSDT": "Tensor (TNSR)",
    "WUSDT": "Wormhole (W)",
    "ZROUSDT": "LayerZero (ZRO)",
    "IOUSDT": "io.net (IO)",
    "TONUSDT": "Toncoin (TON)",
    "JUPUSDT": "Jupiter (JUP)",
    "FETUSDT": "Fetch.ai (FET)",
    "AGIXUSDT": "SingularityNET (AGIX)",
    "OCEANUSDT": "Ocean Protocol",
    "WLDUSDT": "Worldcoin (WLD)",
    "GALAUSDT": "Gala Games (GALA)",
    "ENJUSDT": "Enjin Coin (ENJ)",
    "ILVUSDT": "Illuvium (ILV)",
    "IMXUSDT": "Immutable X (IMX)",
    "BEAMXUSDT": "Beam (BEAMX)",
    "ONDOUSDT": "Ondo Finance",
    "LDOUSDT": "Lido DAO (LDO)",
    "TIAUSDT": "Celestia (TIA)",
    "SEIUSDT": "Sei Network (SEI)",
    "ORDIUSDT": "Ordinals (ORDI)",
    "PENDLEUSDT": "Pendle Finance",
    "XMRUSDT": "Monero (XMR)",
    "ZECUSDT": "Zcash (ZEC)",
    "DASHUSDT": "Dash (DASH)",
    "CROUSDT": "Cronos (CRO)",
    "ARUSDT": "Arweave (AR)",
    "GRTUSDT": "The Graph (GRT)",
    "COMPUSDT": "Compound (COMP)",
    "MKRUSDT": "Maker (MKR)",
    "SNXUSDT": "Synthetix (SNX)",
    "CRVUSDT": "Curve DAO (CRV)",
    "LRCUSDT": "Loopring (LRC)",
    "1INCHUSDT": "1inch Network",
    "SUSHIUSDT": "SushiSwap (SUSHI)",
    "GMXUSDT": "GMX (GMX)",
    "DYDXUSDT": "dYdX (DYDX)",
    "CHZUSDT": "Chiliz (CHZ)",
    "ZILUSDT": "Zilliqa (ZIL)",
    "HOTUSDT": "Holo (HOT)",
    "RVNUSDT": "Ravencoin (RVN)",
    "KAVAUSDT": "Kava (KAVA)",
    "ROSEUSDT": "Oasis Network (ROSE)",
    "TRBUSDT": "Tellor (TRB)",
    "POPCATUSDT": "Popcat (POPCAT)",
    "TURBOUSDT": "Turbo (TURBO)",
    "MEWUSDT": "Cat in a Dogs World",
    "BRETTUSDT": "Brett (BRETT)",
    "NOTUSDT": "Notcoin (NOT)",
    "PENGUUSDT": "Pudgy Penguins",
    "PNUTUSDT": "Peanut the Squirrel",
    "HMSTRUSDT": "Hamster Kombat",
    "CATIUSDT": "Catizen (CATI)",
    "DOGUSDT": "DOG GO TO THE MOON",
    "NEIROUSDT": "Neiro (NEIRO)",
    "GOATUSDT": "Goatseus Maximus",
    "MOODENGUSDT": "Moo Deng (MOODENG)",
    "BOMEUSDT": "Book of MEME",
    "ZEUSUSDT": "Zeus Network",
    "BBUSDT": "BounceBit (BB)",
    "LISTAUSDT": "Lista DAO",
    "BANANAUSDT": "Banana Gun",
    "ZETAUSDT": "ZetaChain",
    "AERGOUSDT": "Aergo (AERGO)",
    "BIOUSDT": "Bio Protocol",
    "GUSDT": "G (Gravity)",
    "NEIROETHUSDT": "Neiro Ethereum",
    "EIGENUSDT": "EigenLayer",
    "SATSUSDT": "SATS (Ordinals)",
    "RATSUSDT": "RATS (Ordinals)",
    "KCSUSDT": "KuCoin Token (KCS)",
    "OKBUSDT": "OKB (OKX)",
    "GTUSDT": "GateToken (GT)",
    "BGBUSDT": "Bitget Token (BGB)",
    "LEOUSDT": "UNUS SED LEO",
    "BTTUSDT": "BitTorrent (BTT)",
    "STORJUSDT": "Storj (STORJ)",
    "SCUSDT": "Siacoin (SC)",
    "ANKRUSDT": "Ankr (ANKR)",
    "HNTUSDT": "Helium (HNT)",
    "IOTXUSDT": "IoTeX (IOTX)",
    "AKTUSDT": "Akash Network",
    "PYTHUSDT": "Pyth Network",
    "BANDUSDT": "Band Protocol",
    "API3USDT": "API3",
    "SCRTUSDT": "Secret Network",
    "KDAUSDT": "Kadena (KDA)",
    "CFXUSDT": "Conflux (CFX)",
    "CKBUSDT": "Nervos Network",
    "JASMYUSDT": "JasmyCoin (JASMY)",
    "FLUXUSDT": "Flux (FLUX)",
    "ONTUSDT": "Ontology (ONT)",
    "IOSTUSDT": "IOST (IOST)",
    "DGBUSDT": "DigiByte (DGB)",
    "ONEUSDT": "Harmony (ONE)",
    "CELRUSDT": "Celer Network",
    "COTIUSDT": "COTI (COTI)",
    "DUSKUSDT": "Dusk Network",
    "BNTUSDT": "Bancor (BNT)",
    "BATUSDT": "Basic Attention Token",
    "ZRXUSDT": "0x Protocol (ZRX)",
    "CVXUSDT": "Convex Finance",
    "FXSUSDT": "Frax Share (FXS)",
    "CAKEUSDT": "PancakeSwap",
    "JOEUSDT": "Trader Joe (JOE)",
    "STGUSDT": "Stargate Finance",
    "RAYUSDT": "Raydium (RAY)",
    "OMUSDT": "MANTRA (OM)",
    "CFGUSDT": "Centrifuge (CFG)",
    "POLYXUSDT": "Polymesh (POLYX)",
    "RPLUSDT": "Rocket Pool (RPL)",
    "ANKRETHUSDT": "Ankr Staked ETH",
    "STETHUSDT": "Lido Staked ETH",
    "YGGUSDT": "Yield Guild Games",
    "PYRUSDT": "Vulcan Forged PYR",
    "ALICEUSDT": "My Neighbor Alice",
    "VOXELUSDT": "Voxies (VOXEL)",
    "PIXELUSDT": "Pixels (PIXEL)",
    "PORTALUSDT": "Portal (PORTAL)",
    "ACEUSDT": "Fusionist (ACE)",
    "XAIUSDT": "Xai (XAI)",
    "MAVIAUSDT": "Heroes of Mavia",
    "BIGTIMEUSDT": "Big Time (BIGTIME)",
    "PRIMEUSDT": "Echelon Prime",
    "ZKJUSDT": "Polyhedra Network",
    "BLASTUSDT": "Blast (BLAST)",
    "AVAILUSDT": "Avail (AVAIL)",
    "ORDERUSDT": "Orderly Network",
    "COOKIEUSDT": "Cookie (COOKIE)",
    "MOVEUSDT": "Movement (MOVE)",
    "GRASSUSDT": "Grass (GRASS)",
    "MYROUSDT": "Myro (MYRO)",
    "SLERFUSDT": "Slerf (SLERF)",
    "SAMOUSDT": "Samoyed Coin",
    "NFPUSDT": "NFPrompt (NFP)",
    "NMRUSDT": "Numeraire (NMR)",
    "RLCUSDT": "iExec RLC",
    "CTXCUSDT": "Cortex (CTXC)",
    "ARKMUSDT": "Arkham (ARKM)",
    "MCUSDT": "Merit Circle",
    "TLMUSDT": "Alien Worlds",
    "DARUSDT": "Mines of Dalarnia",
    "SCRUSDT": "Scroll (SCR)",
    "SSVUSDT": "SSV Network",
    "ENSUSDT": "Ethereum Name Service",
    "KASUSDT": "Kaspa (KAS)",

    # ── YENİ BIST HİSSELERİ ──────────────────────────────────────────
    "AGROT.IS": "Agrotech Yüksek Teknoloji",
    "AKENR.IS": "Akenrji Elektrik",
    "AKSGY.IS": "Akış GYO",
    "AKSUE.IS": "Aksu Enerji",
    "ALCTL.IS": "Alcatel Lucent Teletaş",
    "ARDYZ.IS": "Ard Bilişim Teknolojileri",
    "ARSAN.IS": "Arsan Tekstil",
    "ASUZU.IS": "Anadolu Isuzu",
    "ATEKS.IS": "Akin Tekstil",
    "ATLAS.IS": "Atlas Yatırım Ortaklığı",
    "AVPGY.IS": "Avrupa GYO",
    "AVTUR.IS": "Avrasya Petrol",
    "BASCM.IS": "Bastak Madencilik",
    "BINHO.IS": "Binho Yapı",
    "BIOEN.IS": "Biotrend Enerji",
    "BLCYT.IS": "Bilici Yatırım",
    "BMELK.IS": "Bimel Kauçuk",
    "BORLS.IS": "Borlease Otomotiv",
    "BRKSN.IS": "Berksan Kauçuk",
    "CATES.IS": "Çates Elektrik",
    "CLEBI.IS": "Çelebi Hava Servisi",
    "CONSE.IS": "Consus Enerji",
    "CUSAN.IS": "Çuhadaroğlu Metal",
    "DARDL.IS": "Dardanel Önentaş",
    "DENGE.IS": "Denge Yatırım",
    "DERHL.IS": "Derlüks Deri",
    "DESA.IS": "Desa Deri",
    "DESPC.IS": "Despec Bilgisayar",
    "DGATE.IS": "Datagate Bilgisayar",
    "DGKLB.IS": "Doğtaş Kelebek Mobilya",
    "DGNMO.IS": "Doğanlar Mobilya",
    "DIRIT.IS": "Diriteks Diriliş",
    "DITAS.IS": "Ditaş Doğan",
    "DMSAS.IS": "Demisaş Döküm",
    "DNISI.IS": "Dinamik Isı",
    "DURDO.IS": "Duran Doğan",
    "DYOBY.IS": "DYO Boya",
    "EBEBK.IS": "Ebebek Mağazacılık",
    "EDATA.IS": "E-Data Teknoloji",
    "EDIP.IS": "Edip Gayrimenkul",
    "EFORC.IS": "Efor Çay",
    "EGPRO.IS": "Ege Profil",
    "EGGUB.IS": "Ege Gübre",
    "EKSUN.IS": "Eksun Gıda",
    "EKSYO.IS": "Eks Yatırım",
    "EMKEL.IS": "Emek Elektrik",
    "EMNIS.IS": "Eminiş Ambalaj",
    "ENGY.IS": "Enerya Enerji",
    "ENSRI.IS": "Ensari Deri",
    "ERBOS.IS": "Erbosan Boru",
    "ERSU.IS": "Ersu Gıda",
    "ESCOM.IS": "Escort Teknoloji",
    "ESEN.IS": "Esenboğa Elektrik",
    "ETILR.IS": "Etiler Gıda",
    "EUREN.IS": "Europower Enerji",
    "EYG.IS": "Evyap GYO",
    "EYUPO.IS": "Eyüpoğlu Yatırım",
    "FADE.IS": "Fade Gıda",
    "FLAP.IS": "Flap Kongre",
    "FMIZP.IS": "F-M İzmit Piston",
    "FONET.IS": "Fonet Bilgi Teknolojileri",
    "FORMT.IS": "Formet Çelik",
    "FRIGO.IS": "Frigo-Pak Gıda",
    "GEDIK.IS": "Gedik Yatırım",
    "GEDZA.IS": "Gediz Ambalaj",
    "GLBMD.IS": "Global Menkul Değerler",
    "GLRYH.IS": "Güleryüz Karoser",
    "GRNYO.IS": "Garanti Yatırım Ortaklığı",
    "HDFGS.IS": "HDF Girişim Sermayesi",
    "HUNER.IS": "Huner Yapı",
    "HURGZ.IS": "Hürriyet Gazetecilik",
    "ICBCT.IS": "ICBC Turkey Bank",
    "IDGYO.IS": "İdealist GYO",
    "IEYHO.IS": "Işıklar Enerji",
    "IHEVA.IS": "İhlas Ev Aletleri",
    "INSU.IS": "İnsü Madencilik",
    "INTEM.IS": "İntema İnşaat",
    "INVEO.IS": "Inveo Yatırım",
    "IPEKE.IS": "İpek Doğal Enerji",
    "ISBIR.IS": "İşbir Holding",
    "ISFIN.IS": "İş Finansal Kiralama",
    "ISKPL.IS": "İşik Plastik",
    "ISSEN.IS": "İş Sendikası",
    "IZFAS.IS": "İzmir Fırça",
    "IZINV.IS": "İz Yatırım",
    "KAPLM.IS": "Kaplamin Ambalaj",
    "KBORU.IS": "Kuzey Boru",
    "KFEIN.IS": "Kafein Yazılım",
    "KLGYO.IS": "Kiler GYO",
    "KLVUK.IS": "Kale Vana",
    "KNFRT.IS": "Konfrut Gıda",
    "KRPLS.IS": "Koroplast",
    "KRTEK.IS": "Kartek Holding",
    "KTSKR.IS": "Kütahya Şeker",
    "KUYAS.IS": "Kuyaş Yatırım",
    "LKMNH.IS": "Lokman Hekim Sağlık",
    "MAALT.IS": "Marmaris Altınyunus",
    "MAGEN.IS": "Magen Enerji",
    "MAKTK.IS": "Makina Takım",
    "MARTI.IS": "Martı Otel",
    "MEGAP.IS": "Mega Polietilen",
    "MEPET.IS": "Mepet Petrolden",
    "MERIT.IS": "Merit Turizm",
    "MOGAN.IS": "Moğan Enerji",
    "MSGYO.IS": "Mistral GYO",
    "MTRKS.IS": "Matriks Bilgi Dağıtım",
    "MZHLD.IS": "Mazhar Zorlu",
    "OBAMS.IS": "Oba Makarna",
    "OYLUM.IS": "Oylum Sınai",
    "OZGYO.IS": "Özak GYO",
    "OZKGY.IS": "Özderici GYO",
    "PAGYO.IS": "Panora GYO",
    "PAPIL.IS": "Papilon Savunma",
    "PEKGY.IS": "Peker GYO",
    "PENGD.IS": "Penguen Gıda",
    "PLTUR.IS": "Platform Turizm",
    "PRZMA.IS": "Prizma Pres",
    "PSGYO.IS": "Pasifik GYO",
    "QUAGR.IS": "Qua Granite",
    "RODRG.IS": "Rodrigo Tekstil",
    "RTALB.IS": "RTA Laboratuvarları",
    "RYGYO.IS": "Reysaş GYO",
    "SAMAT.IS": "Samatlı Yatırım",
    "SEGMN.IS": "Segmen Kardemir",
    "SEKFK.IS": "Şeker Finansal Kiralama",
    "SEYKM.IS": "Seyitler Kimya",
    "SMART.IS": "Smartiks Yazılım",
    "SMRVG.IS": "Smart Güneş",
    "SNICA.IS": "Sanica Isı",
    "SONME.IS": "Sönmez Filament",
    "SRVGY.IS": "Servet GYO",
    "TACTR.IS": "Taç Tarım",
    "TGSAS.IS": "TGS Dış Ticaret",
    "TKURU.IS": "T Kuru Yatırım",
    "TLMAN.IS": "Tolman Turizm",
    "TMPOL.IS": "Temapol Polimer",
    "TRCAS.IS": "Turcas Petrol",
    "TUKAS.IS": "Tukaş Gıda",
    "UFUK.IS": "Ufuk Yatırım",
    "ULAS.IS": "Ulaşlar Turizm",
    "ULUFA.IS": "Ulusoy Un",
    "VERTU.IS": "Vertu Motor",
    "VKING.IS": "Viking Kağıt",
    "VRGYO.IS": "Vera GYO",
    "YBTAS.IS": "Yibitaş Ticaret",
    "YEREN.IS": "Yeren Enerji",
    "YESIL.IS": "Yeşil Yatırım",
    "YONGA.IS": "Yonga Mobilya",
    "ENJSA.IS": "Enerjisa Enerji",
    "AYGAZ.IS": "Aygaz",
    "CIMEN.IS": "Çimsa Çimento",
}
